config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'zeldaquiz', to: 'pages#zeldaquiz', as: 'zeldaquiz'

  # Nest the about route under zeldaquiz
  get 'zeldaquiz/about', to: 'pages#about', as: 'zeldaquiz_about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    
  end

  def zeldaquiz

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_random_image
    image_path_prefix = "app/assets/images/"
    image_files = Dir.glob("#{image_path_prefix}guess-images/*")
    image_files.sample.split(image_path_prefix)[1]
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zelda Game</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css", integrity: "sha384-..." %>
    <link href="https://fonts.cdnfonts.com/css/the-wild-breath-of-zelda" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container-about">

  <div class="fairy">
    <div class="wings"></div>
    <div class="glow">
      <div class="sparkle"></div>
      <div class="sparkle"></div>
      <div class="sparkle"></div>
      <div class="sparkle"></div>
      <div class="sparkle"></div>
    </div>
  </div>

  <div class="about">
    <h1>About</h1>
    <h2>Welcome to the Zelda Quiz</h2>
    <h3>Disclaimer</h3>


    <p>I decided to do this page to practice my skills creating in the digital world
    <br>If you like it...Please share it!
    <br>If you don't like it...Share it to your enemies👹</p>
    <p>I don't own any type of property of Zelda or Nintendo's games.<br>I will not charge or make any money out of this game. <br> Nintendo... don't get mad! <br>I just love the Zelda universe so much :)</p>
  </div>
  <div class="button-back">
      <%= link_to zeldaquiz_path, class: "triforce-button", id: "go-back-button" do %>
      <%= image_tag("triforce.png", alt: "Go Back") %>
      Go Back
    <% end %>
  </div>
</div>

app/views/pages/zeldaquiz.html.erb
<div class="navbar">
  <h1>Zelda Quiz</h1>
</div>

<div class="container">

  <div class="score">
    <div class="now">
      <p>NOW</p>
      <p>0</p>
    </div>
    <div class="life">
      <i class="fa-solid fa-heart"></i>
      <i class="fa-solid fa-heart"></i>
      <i class="fa-solid fa-heart"></i>
    </div>
    <div class="top">
      <p>TOP</p>
      <p>15</p>
    </div>
  </div>

  <div class="game-screen">
    <div class="guess-image">
      <%= image_tag get_random_image %>
    </div>
  </div>

  <div class="game-keyboard">
    <button class="image-button">
    <img src="<%= asset_path("triforce.png") %>" alt="Button Image">
    </button>
    <p>Use the Triforce to play!</p>
  </div>

  <div class="log">
    <p>You have 3 attempts left</p>
  </div>

</div>

<div class="footer">
  <a href="https://github.com" target="_blank">
    <i class="fab fa-github" style="color: white;"></i>
  </a>
  <%= link_to "About", zeldaquiz_about_path, class: "btn-about" %>
  <audio id="sound" src="<%= asset_path('secret.wav') %>" autoplay></audio>
  <p>Created in 2024</p>

</div>